// src/app/pages/player/course-choice/course-choice.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {ReadingStoreService} from '../../../services/reading-store.service';
import {Reading} from '../../../classes/reading';
import {Content} from '../../../classes/contents/content';

@Component({
    selector: 'course-choice',
    templateUrl: './course-choice.component.html',
    styleUrls: ['./course-choice.component.scss'],
})
export class CourseChoiceComponent implements OnInit {

    @Input() content: Content;
    @Input() epocId: string;
    @Output() chosen = new EventEmitter();

    resolver;
    answer;
    reading: Reading;

    constructor(
        private readingStore: ReadingStoreService
    ) {}

    ngOnInit(): void {
        this.resolver = this.content.conditionResolver;

        this.readingStore.readings$.subscribe(readings => {
            if (readings) {
                this.reading = readings.find(item => item.epocId === this.epocId);

                const choices = this.reading.choices.find(c => c.id === this.content.id);

                if (choices) {
                    this.answer = choices.responses;
                }
            }
        });
    }

    saveChoice() {
        const flags = this.content.conditionResolver.conditionalFlag.find(condition => condition.value === this.answer).flags;
        const flagsToRemove = this.content.conditionResolver.conditionalFlag.reduce((acc, condition) => acc.concat(condition.flags), []);
        this.readingStore.saveChoices(this.epocId, this.content.id, this.answer, flags, flagsToRemove);
        this.chosen.emit();
    }

    selectAnswer(answer) {
        this.answer = answer;
    }
}

<div class="question-card">
  <div class="statement">
    <b>{{resolver.label}}</b>
  </div>

  <ion-radio-group [value]="answer">
    <ion-item [lines]="'none'" *ngFor="let choice of resolver.choices" (click)="selectAnswer(choice.value)">
      <ion-radio mode="md" slot="start" [value]="choice.value" [disabled]="disabled"></ion-radio>
      <ion-label class="ion-text-wrap">{{choice.label}}</ion-label>
    </ion-item>
  </ion-radio-group>

  <button (click)="saveChoice($event)">Valider</button>
</div>

// src/views/epoc/content/CourseChoice.vue
<script setup lang="ts">
import { computed } from 'vue';
import { storeToRefs } from 'pinia';
import { ChoiceCondition } from '@epoc/epoc-types/dist/v1';
import { Content } from '@/types/contents/content';
import { useReadingStore } from '@/stores/readingStore';
import {trackEvent} from '@/utils/matomo';

const props = defineProps<{
  content: Content;
  epocId: string;
}>();

const emit = defineEmits(['chosen']);

const readingStore = useReadingStore();
const { readings } = storeToRefs(readingStore);

const resolver = computed(() => (props.content as any).conditionResolver);
const reading = computed(() => readings.value.find((item) => item.epocId === props.epocId));
const answer = computed(() => {
  const choice = reading.value?.choices?.find((c) => c.id === props.content.id);
  return choice ? choice.responses : null;
});

const selectAnswer = (selectedAnswer: any) => {
  const choiceCondition = props.content as unknown as ChoiceCondition;

  const flags = choiceCondition.conditionResolver.conditionalFlag.find(
      condition => condition.value === selectedAnswer
  )?.flags || [];

  const flagsToRemove = choiceCondition.conditionResolver.conditionalFlag.reduce(
      (acc, condition) => acc.concat(condition.flags), [] as string[]
  );

  trackEvent(props.epocId, `${props.epocId} / CourseChoice chosen ${props.content.id} ${props.content?.title} / Selected answer : ${selectedAnswer}`);

  readingStore.saveChoices(
      props.epocId,
      props.content.id,
      selectedAnswer,
      flags,
      flagsToRemove
  );

  setTimeout(() => {
    emit('chosen');
  }, 200);
};
</script>

<template>
  <div v-if="resolver" class="container">
    <div class="statement">
      <b>{{ resolver.label }}</b>
    </div>

    <div class="choices">
      <button
          v-for="choice in resolver.choices"
          :key="choice.value"
          :class="{ 'selected': choice.value === answer }"
          @click="selectAnswer(choice.value)"
      >
        {{ choice.label }}
      </button>
    </div>
  </div>
</template>

<style scoped lang="scss">
.statement {
  margin: 2rem 0;
  text-align: center;
  b {
    line-height: 1;
  }
}

.choices {
  button {
    display: block;
    width: 100%;
    margin-top: 1em;
    padding: 1em;
    background: var(--ion-color-content);
    font-weight: bold;
    color: var(--ion-color-text);
    border-radius: 4px;
    border: 1px solid var(--ion-color-text);
    cursor: pointer;
    transition: all 0.2s ease-in-out;

    &.selected {
      color: var(--ion-color-content);
      background: var(--ion-color-text);
    }

    &:active {
      opacity: 0.7;
    }
  }
}
</style>
