// src/app/pages/player/assessment/components/multiple-choice/multiple-choice.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {Question} from '../../../../../classes/contents/assessment';

@Component({
    selector: 'multiple-choice',
    templateUrl: '../multiple-choice/multiple-choice.component.html',
    styleUrls: ['../multiple-choice/multiple-choice.component.scss'],
})
export class MultipleChoiceComponent {

    @Input('question') question: Question;
    @Input('disabled') disabled: boolean;
    @Output() onSelectAnswer = new EventEmitter<any>();

    selectedAnswers = [];

    constructor() {}

    selectAnswer(answer) {
        const index = this.selectedAnswers.indexOf(answer.detail.value);
        if (answer.detail.checked && index === -1) {
            this.selectedAnswers.push(answer.detail.value);
        } else {
            if (index >= 0) {
                this.selectedAnswers.splice(index, 1);
            }
        }

        this.onSelectAnswer.emit(this.selectedAnswers);
    }
}

<ion-list>
  <ion-item [lines]="'none'" *ngFor="let response of question.responses">
    <ion-checkbox mode="md" slot="start" [value]="response.value" [disabled]="disabled" (ionChange)="selectAnswer($event)"></ion-checkbox>
    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
  </ion-item>
</ion-list>

// src/components/questions/MultipleChoice.vue
<script setup lang="ts">
import { MultipleChoiceQuestion } from '@/types/contents/assessment';
import { PropType, ref } from 'vue';
import { IonItem, IonCheckbox, IonLabel, IonList } from '@ionic/vue';

const props = defineProps({
    question: { type : Object as PropType<(MultipleChoiceQuestion)>, required: true},
    disabled: Boolean,
    userPreviousResponse: Array<String>,
})

const emits = defineEmits<{
  userHasResponded: [userResponses: any[]]; 
}>()

const selectedAnswers = ref<any[]>((props.userPreviousResponse && props.userPreviousResponse.length > 0) ? props.userPreviousResponse : []);

const selectAnswer = (answer: any) => {
    const index = selectedAnswers.value.indexOf(answer.detail.value);
    if (answer.detail.checked && index === -1) {
        selectedAnswers.value.push(answer.detail.value);
    } else {
        if (index >= 0) {
            selectedAnswers.value.splice(index, 1);
        }
    }
    emits('userHasResponded', selectedAnswers.value);
}
</script>

<template>
<ion-list>
  <ion-item v-for="response of question.responses" lines="none">
    <ion-checkbox mode="md" slot="start" :value="response.value" @ionChange="selectAnswer"
                  :checked="selectedAnswers.indexOf(response.value) !== -1" :disabled="disabled">
    </ion-checkbox>
    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
  </ion-item>
</ion-list>
</template>

<style>
</style>
