// src/components/questions/MultipleChoice.vue
<script setup lang="ts">
import { MultipleChoiceQuestion } from '@/types/contents/assessment';
import { PropType, ref } from 'vue';
import { IonItem, IonCheckbox, IonLabel, IonList } from '@ionic/vue';

const props = defineProps({
    question: { type : Object as PropType<(MultipleChoiceQuestion)>, required: true},
    disabled: Boolean,
    userPreviousResponse: Array<String>,
})

const emits = defineEmits<{
  userHasResponded: [userResponses: any[]]; 
}>()

const selectedAnswers = ref<any[]>((props.userPreviousResponse && props.userPreviousResponse.length > 0) ? props.userPreviousResponse : []);

const selectAnswer = (answer: any) => {
    const index = selectedAnswers.value.indexOf(answer.detail.value);
    if (answer.detail.checked && index === -1) {
        selectedAnswers.value.push(answer.detail.value);
    } else {
        if (index >= 0) {
            selectedAnswers.value.splice(index, 1);
        }
    }
    emits('userHasResponded', selectedAnswers.value);
}
</script>

<template>
<ion-list>
  <ion-item v-for="response of question.responses" lines="none">
    <ion-checkbox mode="md" slot="start" :value="response.value" @ionChange="selectAnswer"
                  :checked="selectedAnswers.indexOf(response.value) !== -1" :disabled="disabled">
    </ion-checkbox>
    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
  </ion-item>
</ion-list>
</template>

<style>
</style>

// src/app/components/questions/multiple-choice/multiple-choice.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {MultipleChoiceQuestion} from 'src/app/classes/contents/assessment';
import {AbstractQuestionComponent} from '../abstract-question.component';

@Component({
    selector: 'multiple-choice',
    templateUrl: '../multiple-choice/multiple-choice.component.html',
    styleUrls: ['../multiple-choice/multiple-choice.component.scss'],
})
export class MultipleChoiceComponent extends AbstractQuestionComponent implements OnInit {

    @Input() question: MultipleChoiceQuestion;

    // Array to loop on
    selectedAnswers = [];

    constructor() {
        super();
    }

    ngOnInit() {
        if (this.userPreviousResponse && this.userPreviousResponse.length > 0) {
            this.selectedAnswers = this.userPreviousResponse;
        }
    }

    selectAnswer(answer) {
        const index = this.selectedAnswers.indexOf(answer.detail.value);
        if (answer.detail.checked && index === -1) {
            this.selectedAnswers.push(answer.detail.value);
        } else {
            if (index >= 0) {
                this.selectedAnswers.splice(index, 1);
            }
        }
        this.userResponse.emit(this.selectedAnswers);
    }
}

<p class="nbCorrect">{{selectHeader}}</p>
<ion-list>
  <ion-item *ngFor="let response of question.responses"
            [lines]="'none'"
            [ngClass]="{
            'disabled': correctionState,
            'correct': correctionState && selectClass[question.responses.indexOf(response)] === 'correct',
            'incorrect': correctionState && selectClass[question.responses.indexOf(response)] === 'incorrect'}">
    <ion-checkbox mode="md" slot="start"
                  [value]="response.value"
                  (ionChange)="selectAnswer($event)"
                  [checked]="this.correctionState && this.selectValue[this.question.responses.indexOf(response)]"
                  [disabled]="correctionState">

    </ion-checkbox>
    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
  </ion-item>
</ion-list>
