// src/app/components/corrections/correction-reorder/correction-reorder.component.ts
import {Component, Input, OnInit} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import {DragAndDropquestion, Question} from 'src/app/classes/contents/assessment';

@Component({
  selector: 'correction-reorder',
  templateUrl: './correction-reorder.component.html',
  styleUrls: ['../correction-common.scss', './correction-reorder.component.scss'],
})
export class CorrectionReorderComponent implements OnInit {
  @Input() question: DragAndDropquestion;
  @Input() userResponses: any[];

  correction: {correct: boolean, label: string, correctResponse: string}[] = [];
  rightResponses = 0;
  wrongResponses = 0;

  constructor(public translate:TranslateService) { }

  ngOnInit () {
    this.correction = this.userResponses.map((response, index) => {
      const rightIndex = this.question.responses.findIndex(r => r.value === response);
      const correct =  rightIndex === index;
      correct ? this.rightResponses++ : this.wrongResponses++;
      return {
        correct,
        label: response.label,
        correctResponse: this.translate.instant('QUESTION.CORRECTION.POSITION') + (rightIndex+1)
      }
    });
  }
}

<ng-container  *ngIf="correction">
  <div class="correction-specs">
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
      <div class="correction-spec-value">{{rightResponses}} {{'QUESTION.CORRECTION.CORRECT_ANSWERS' | plural:rightResponses | translate}}</div>
    </div>
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
      <div class="correction-spec-value">{{wrongResponses}} {{'QUESTION.CORRECTION.WRONG_ANSWERS' | plural:wrongResponses | translate}}</div>
    </div>
  </div>
  <h4>{{'QUESTION.CORRECTION.RESPONDED' | translate}}</h4>
  <div class="item" *ngFor="let response of correction; let index = index;">
    <span class="item-index">{{index+1}}</span>
    <ion-item lines="none">
      <div class="correction-icon correct" *ngIf="response.correct"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
      <div class="correction-icon incorrect" *ngIf="!response.correct"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
      <ion-label class="ion-text-wrap" color="inria-blue">
        {{response.label}}
        <div class="correction-right" *ngIf="response.correct">{{'QUESTION.CORRECTION.TRUE' | translate}}</div>
        <div class="correction-wrong" *ngIf="!response.correct">{{'QUESTION.CORRECTION.FALSE' | translate}}</div>
        <div class="correction-right-answer" *ngIf="!response.correct">
          <b>{{'QUESTION.CORRECTION.CORRECT' | translate}}</b><span>{{response.correctResponse}}</span>
        </div>
      </ion-label>
    </ion-item>
  </div>
  <ng-container>
    <h4>{{'QUESTION.CORRECTION.CORRECT_RANKING' | translate}}</h4>
    <div class="item" *ngFor="let response of question.responses; let index = index;">
      <span class="item-index correct">{{index+1}}</span>
      <ion-item lines="none">
        <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
        <ion-reorder slot="end">
          <ion-icon aria-hidden="true" src="/assets/icon/slider.svg"></ion-icon>
        </ion-reorder>
      </ion-item>
    </div>
  </ng-container>
</ng-container>

// src/components/corrections/CorrectionReorder.vue
<script setup lang="ts">
import type { DragAndDropQuestion } from '@/types/contents/assessment';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { IonIcon, IonItem, IonLabel, IonReorder } from '@ionic/vue';
import { checkmarkOutline, closeOutline, chevronDownOutline } from 'ionicons/icons';

const props = defineProps<{
    question: DragAndDropQuestion;
    userResponses: any[];
}>();

const { t } = useI18n();

const correction = computed(() =>
    props.userResponses.map((response, index) => {
        const rightIndex = props.question.responses.findIndex((r) => r.value === response);
        const correct = rightIndex === index;

        return {
            correct,
            label: response.label,
            correctResponse: t('QUESTION.CORRECTION.POSITION') + (rightIndex + 1),
            feedback: props.question.responses[rightIndex].feedback,
        };
    })
);

const rightResponses = computed(() => correction.value.filter((c) => c.correct).length);
const wrongResponses = computed(() => correction.value.filter((c) => !c.correct).length);
</script>

<template>
    <div v-if="correction">
        <div class="correction-specs">
            <div class="correction-spec">
                <div class="correction-spec-icon">
                    <IonIcon aria-hidden="true" :icon="checkmarkOutline" />
                </div>
                <div class="correction-spec-value">
                    {{ rightResponses }} {{ t('QUESTION.CORRECTION.CORRECT_ANSWERS', rightResponses) }}
                </div>
            </div>

            <div class="correction-spec">
                <div class="correction-spec-icon">
                    <IonIcon aria-hidden="true" :icon="closeOutline" />
                </div>
                <div class="correction-spec-value">
                    {{ wrongResponses }} {{ t('QUESTION.CORRECTION.WRONG_ANSWERS', wrongResponses) }}
                </div>
            </div>
        </div>

        <h4>{{ t('QUESTION.CORRECTION.RESPONDED') }}</h4>

        <div v-for="(response, index) of correction" :key="index" class="item">
            <span class="item-index">{{ Number(index) + 1 }}</span>

            <IonItem lines="none">
                <div v-if="response.correct" class="correction-icon correct">
                    <IonIcon aria-hidden="true" :icon="checkmarkOutline" />
                </div>
                <div v-else class="correction-icon incorrect">
                    <IonIcon aria-hidden="true" :icon="closeOutline" />
                </div>

                <IonLabel class="ion-text-wrap" color="inria-blue">
                    {{ response.label }}
                    <div v-if="response.correct" class="correction-right">
                        {{ t('QUESTION.CORRECTION.TRUE') }}
                    </div>
                    <template v-else>
                        <div class="correction-wrong">
                            {{ t('QUESTION.CORRECTION.FALSE') }}
                        </div>

                        <div class="correction-right-answer">
                            <b>{{ t('QUESTION.CORRECTION.CORRECT') }}</b>
                            <span>{{ response.correctResponse }}</span>
                        </div>
                    </template>

                    <details v-if="response.feedback" :open="!response.correct">
                        <summary>
                            {{ t('QUESTION.PREVIEW.EXPLANATION') }}
                            <IonIcon :icon="chevronDownOutline" />
                        </summary>
                        <div>{{ response.feedback }}</div>
                    </details>
                </IonLabel>
            </IonItem>
        </div>

        <h4>{{ t('QUESTION.CORRECTION.CORRECT_RANKING') }}</h4>
        <div v-for="(response, index) of question.responses" :key="index" class="item">
            <span class="item-index correct">{{ Number(index) + 1 }}</span>

            <IonItem lines="none">
                <IonLabel class="ion-text-wrap">{{ response.label }}</IonLabel>
                <IonReorder slot="end">
                    <IonIcon aria-hidden="true" src="/assets/icon/slider.svg" />
                </IonReorder>
            </IonItem>
        </div>
    </div>
</template>

<style scoped lang="scss">
@use '@/theme/correction.scss';

div.item {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 1rem;
    box-shadow: none !important;
    ion-item {
        flex-grow: 1;
        margin-left: 0.5rem;
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        background: var(--ion-color-item);
        --padding-start: 0;
        --padding-top: 0;
        --padding-bottom: 0;
        --min-height: 0;
        --background: var(--ion-color-item);

        ion-label {
            margin: 0 0.5rem 0 0;
        }
    }
}

.item-index {
    width: 1.2rem;
    height: 1.2rem;
    padding-top: 0.1rem;
    font-size: 0.8rem;
    font-weight: bold;
    line-height: 1.2rem;
    text-align: center;
    border-radius: 1.2rem;
    background: var(--ion-color-item);

    &.correct {
        background: var(--ion-color-inria-correct);
        color: white;
    }
}
</style>
