// src/app/components/corrections/correction-sort/correction-sort.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {DragAndDropquestion} from 'src/app/classes/contents/assessment';

@Component({
  selector: 'correction-sort',
  templateUrl: './correction-sort.component.html',
  styleUrls: ['../correction-common.scss', './correction-sort.component.scss'],
})
export class CorrectionSortComponent implements OnInit {
  @Input() question: DragAndDropquestion;
  @Input() userResponses: any[];

  correction: {correct: boolean, label: string, correctResponse: string}[][] = [];
  rightResponses = 0;
  wrongResponses = 0;
  sortGroups:string[];

  constructor() { }

  ngOnInit() {
    this.sortGroups = this.question.correctResponse.map((zone) => zone.label);
    this.correction = this.userResponses.map((group, groupIndex) => {
      return group.map(response => {
        const correct = this.question.correctResponse[groupIndex].values.indexOf(response.value) !== -1;
        correct ? this.rightResponses++ : this.wrongResponses++;
        return {
          correct,
          label: response.label,
          correctResponse: this.question.correctResponse.find(correctGroup => correctGroup.values.indexOf(response.value) !== -1).label
        }
      })
    });
  }

}

<ng-container  *ngIf="correction">
  <div class="correction-specs">
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
      <div class="correction-spec-value">{{rightResponses}} {{'QUESTION.CORRECTION.CORRECT_ANSWERS' | plural:rightResponses | translate}}</div>
    </div>
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
      <div class="correction-spec-value">{{wrongResponses}} {{'QUESTION.CORRECTION.WRONG_ANSWERS' | plural:wrongResponses | translate}}</div>
    </div>
  </div>
  <h4>{{'QUESTION.CORRECTION.RESPONDED' | translate}}</h4>
  <div class="sort-group" *ngFor="let sortGroup of sortGroups; let index = index;">
    <div class="sort-group-label">{{sortGroup}}</div>
    <ion-item lines="none" *ngFor="let response of correction[index]">
      <div class="correction-icon correct" *ngIf="response.correct"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
      <div class="correction-icon incorrect" *ngIf="!response.correct"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
      <ion-label class="ion-text-wrap" color="inria-blue">
        {{response.label}}
        <div class="correction-right" *ngIf="response.correct">{{"QUESTION.CORRECTION.TRUE" | translate}}</div>
        <div class="correction-wrong" *ngIf="!response.correct">{{'QUESTION.CORRECTION.FALSE' | translate}}</div>
        <div class="correction-right-answer" *ngIf="!response.correct">
          <b>{{'QUESTION.CORRECTION.CORRECT' | translate}}</b><span>{{response.correctResponse}}</span>
        </div>
      </ion-label>
    </ion-item>
  </div>
</ng-container>

// src/components/corrections/CorrectionSort.vue
<script setup lang="ts">
import { checkmarkOutline, closeOutline, chevronDownOutline } from 'ionicons/icons';
import { Question, SwipeQuestion } from '@/types/contents/assessment';
import { PropType } from 'vue';

const props = defineProps({
    question: { type : Object as PropType<(Question)>, required: true},
    userResponses: {type: Object as PropType<(any[])>, required: true}
})

type CorrectionType = {correct: boolean, label: string, correctResponse: string, feedback: string}[][]
let rightResponsesNb = 0;
let wrongResponsesNb = 0;
const sortGroups = props.question.correctResponse.map((zone) => zone.label);

const correction: CorrectionType = props.userResponses.map((group, groupIndex) => {
    return group.map((response : any) => {
    const correct = props.question.correctResponse[groupIndex].values.indexOf(response.value) !== -1;
    correct ? rightResponsesNb++ : wrongResponsesNb++;
    return {
        correct,
        label: response.label,
        correctResponse: props.question.correctResponse.find(correctGroup => correctGroup.values.indexOf(response.value) !== -1)?.label,
        feedback: props?.question.responses.find(r => r.value === response.value)?.feedback
    }
    })
});

</script>

<template>
    <div  v-if="correction">
    <div class="correction-specs">
        <div class="correction-spec">
        <div class="correction-spec-icon"><ion-icon aria-hidden="true" :icon="checkmarkOutline"></ion-icon></div>
        <div class="correction-spec-value">{{rightResponsesNb}} {{$t('QUESTION.CORRECTION.CORRECT_ANSWERS', rightResponsesNb)}}</div>
        </div>
        <div class="correction-spec">
        <div class="correction-spec-icon"><ion-icon aria-hidden="true" :icon="closeOutline"></ion-icon></div>
        <div class="correction-spec-value">{{wrongResponsesNb}} {{$t('QUESTION.CORRECTION.WRONG_ANSWERS', wrongResponsesNb)}}</div>
        </div>
    </div>
    <h4>{{$t('QUESTION.CORRECTION.RESPONDED')}}</h4>
    <div class="sort-group" v-for="(sortGroup, index) of sortGroups">
        <div class="sort-group-label">{{sortGroup}}</div>
        <ion-item lines="none" v-for="response of correction[index]">
            <div class="correction-icon correct" v-if="response.correct">
                <ion-icon aria-hidden="true" :icon="checkmarkOutline"></ion-icon>
            </div>
            <div class="correction-icon incorrect" v-if="!response.correct">
                <ion-icon aria-hidden="true" :icon="closeOutline"></ion-icon>
            </div>
            <ion-label class="ion-text-wrap" color="inria-blue">
                {{response.label}}
                <div class="correction-right" v-if="response.correct">{{$t("QUESTION.CORRECTION.TRUE")}}</div>
                <div class="correction-wrong" v-if="!response.correct">{{$t('QUESTION.CORRECTION.FALSE')}}</div>
                <div class="correction-right-answer" v-if="!response.correct">
                    <b>{{$t('QUESTION.CORRECTION.CORRECT')}}</b><span>{{response.correctResponse}}</span>
                </div>
                <details :open="!response.correct" v-if="response.feedback">
                    <summary>{{$t('QUESTION.PREVIEW.EXPLANATION')}} 
                        <ion-icon :icon="chevronDownOutline"></ion-icon>
                    </summary>
                    <div>{{response.feedback}}</div>
                </details>
            </ion-label>
        </ion-item>
    </div>
    </div>
</template>

<style scoped lang="scss">
@use '@/theme/correction.scss';
.sort-group{
  padding:.5rem;
  margin-bottom: 1em;
  background: var(--ion-color-background);
  border: 1px solid var(--ion-color-contrast-2);
  border-radius: 10px;

  &:last-child{
    margin-bottom: 0;
  }

  .sort-group-label{
    flex-grow: 1;
    padding-top: .25em;
    margin-bottom: .5rem;
    font-size: 0.875rem;
    font-weight: bold;
    text-transform: uppercase;
    color: var(--ion-color-text);
  }

  ion-item {
    --background: var(--ion-color-item);

    ion-label {
      color: var(--ion-color-label);
    }
  }
}
</style>
