// src/app/components/corrections/correction-multiple-choice/correction-multiple-choice.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Question} from 'src/app/classes/contents/assessment';

@Component({
  selector: 'correction-multiple-choice',
  templateUrl: './correction-multiple-choice.component.html',
  styleUrls: ['../correction-common.scss', './correction-multiple-choice.component.scss'],
})
export class CorrectionMultipleChoiceComponent implements OnInit {
  @Input() question: Question;
  @Input() userResponses: any[];

  correction: {correct: boolean, label: string, feedback: string}[] = [];
  rightResponses = 0;
  wrongResponses = 0;
  missingResponses: {label: string, feedback: string}[] = [];

  constructor() { }

  ngOnInit() {
    this.question.responses.forEach((response, index) => {
      if ((this.question.correctResponse as Array<string>).indexOf(response.value) !== -1) {
        if (this.userResponses.indexOf(response.value) !== -1) {
          this.correction.push({correct:true, label: response.label, feedback: response.feedback});
          this.rightResponses++;
        } else{
          this.missingResponses.push({label: response.label, feedback: response.feedback})
        }
      } else {
        if (this.userResponses.indexOf(response.value) !== -1) {
          this.correction.push({correct:false, label: response.label, feedback: response.feedback});
          this.wrongResponses++;
        }
      }
    });
  }

}

<ng-container  *ngIf="correction">
  <div class="correction-specs">
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
      <div class="correction-spec-value">{{rightResponses}} {{'QUESTION.CORRECTION.CORRECT_ANSWERS' | plural:rightResponses | translate}}</div>
    </div>
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
      <div class="correction-spec-value">{{wrongResponses}} {{'QUESTION.CORRECTION.WRONG_ANSWERS' | plural:wrongResponses | translate}}</div>
    </div>
    <div class="correction-spec" *ngIf="missingResponses && missingResponses.length">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" name="warning-outline"></ion-icon></div>
      <div class="correction-spec-value">{{missingResponses.length}} {{'QUESTION.CORRECTION.OMISSION' | plural:missingResponses.length | translate}}</div>
    </div>
  </div>
  <h4>{{'QUESTION.CORRECTION.RESPONDED' | translate}}</h4>
  <ion-item lines="none" *ngFor="let response of correction">
    <div class="correction-icon correct" *ngIf="response.correct"><ion-icon aria-hidden="true" name="checkmark-outline"></ion-icon></div>
    <div class="correction-icon incorrect" *ngIf="!response.correct"><ion-icon aria-hidden="true" name="close-outline"></ion-icon></div>
    <ion-label class="ion-text-wrap" color="inria-icon">
      {{response.label}}
      <div class="correction-right" *ngIf="response.correct">{{'QUESTION.CORRECTION.TRUE' | translate}}</div>
      <div class="correction-wrong" *ngIf="!response.correct">{{'QUESTION.CORRECTION.FALSE' | translate}}</div>
    </ion-label>
  </ion-item>
</ng-container>
<ng-container *ngIf="missingResponses && missingResponses.length">
  <h4>{{'QUESTION.CORRECTION.FORGOTTEN' | translate}}</h4>
  <ion-item lines="none" *ngFor="let response of missingResponses">
    <div class="correction-icon">
      <ion-icon aria-hidden="true" name="alert"></ion-icon>
    </div>
    <ion-label class="ion-text-wrap" color="inria-icon">
      {{response}}
      <div class="correction-missing">{{'QUESTION.CORRECTION.WAS_TRUE' | translate}}</div>
    </ion-label>
  </ion-item>
</ng-container>

// src/components/corrections/CorrectionMultipleChoice.vue
<script setup lang="ts">
import { MultipleChoiceQuestion } from '@/types/contents/assessment';
import { PropType } from 'vue';
import { chevronDownOutline } from 'ionicons/icons';
import { IonIcon, IonItem, IonLabel } from '@ionic/vue';
import { alert, checkmarkOutline, closeOutline, warningOutline } from 'ionicons/icons';



const props = defineProps({
    question: { type : Object as PropType<(MultipleChoiceQuestion)>, required: true},
    userResponses: {type: Object as PropType<(any[])>, required: true}
})


type CorrectionType = {correct: boolean, label: string, feedback?: string}
let correction : CorrectionType[] = []
let rightResponsesNb = 0;
let wrongResponsesNb = 0;
let missingResponses : {label: string, feedback?: string}[] = [];

props.question.responses.forEach((response, index) => {
    if ((props.question.correctResponse).indexOf(response.value) !== -1) {
        if (props.userResponses.indexOf(response.value) !== -1) {
            correction.push({correct:true, label: response.label, feedback: response.feedback});
            rightResponsesNb++;
        } else{
            missingResponses.push({label: response.label, feedback: response.feedback})
        }
    } else {
    if (props.userResponses.indexOf(response.value) !== -1) {
        correction.push({correct:false, label: response.label, feedback: response.feedback});
        wrongResponsesNb++;
    }
    }
});


</script>

<template>
<div  v-if="correction">
  <div class="correction-specs">
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" :icon="checkmarkOutline"></ion-icon></div>
      <div class="correction-spec-value">{{rightResponsesNb}} {{$t('QUESTION.CORRECTION.CORRECT_ANSWERS', rightResponsesNb)}}</div>
    </div>
    <div class="correction-spec">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" :icon="closeOutline"></ion-icon></div>
      <div class="correction-spec-value">{{wrongResponsesNb}} {{$t('QUESTION.CORRECTION.WRONG_ANSWERS', wrongResponsesNb)}}</div>
    </div>
    <div class="correction-spec" v-if="missingResponses && missingResponses.length">
      <div class="correction-spec-icon"><ion-icon aria-hidden="true" :icon="warningOutline"></ion-icon></div>
      <div class="correction-spec-value">{{missingResponses.length}} {{$t('QUESTION.CORRECTION.OMISSION', missingResponses.length)}}</div>
    </div>
  </div>
  <h4>{{$t('QUESTION.CORRECTION.RESPONDED')}}</h4>
  <ion-item lines="none" v-for="response of correction">
    <div class="correction-icon correct" v-if="response.correct"><ion-icon aria-hidden="true" :icon="checkmarkOutline"></ion-icon></div>
    <div class="correction-icon incorrect" v-if="!response.correct"><ion-icon aria-hidden="true" :icon="closeOutline"></ion-icon></div>
    <ion-label class="ion-text-wrap" color="inria-icon">
      {{response.label}}
      <div class="correction-right" v-if="response.correct">{{$t('QUESTION.CORRECTION.TRUE')}}</div>
      <div class="correction-wrong" v-if="!response.correct">{{$t('QUESTION.CORRECTION.FALSE')}}</div>
      <details :open="!response.correct" v-if="response.feedback">
        <summary>{{$t('QUESTION.PREVIEW.EXPLANATION')}} <ion-icon :icon="chevronDownOutline"></ion-icon></summary>
        <div>{{response.feedback}}</div>
      </details>
    </ion-label>
  </ion-item>
</div>
<div v-if="missingResponses && missingResponses.length">
  <h4>{{$t('QUESTION.CORRECTION.FORGOTTEN')}}</h4>
  <ion-item lines="none" v-for="response of missingResponses">
    <div class="correction-icon">
      <ion-icon aria-hidden="true" :icon="alert"></ion-icon>
    </div>
    <ion-label class="ion-text-wrap" color="inria-icon">
      {{response.label}}
      <div class="correction-missing">{{$t('QUESTION.CORRECTION.WAS_TRUE')}}</div>
      <details open v-if="response.feedback">
        <summary>{{$t('QUESTION.PREVIEW.EXPLANATION')}} <ion-icon :icon="chevronDownOutline"></ion-icon></summary>
        <div>{{response.feedback}}</div>
      </details>
    </ion-label>
  </ion-item>
</div>
</template>

<style scoped lang="scss">
@use '@/theme/correction.scss';
ion-item {
    --background: var(--ion-color-contrast-2);
}
</style>
