// src/app/components/video-player/video-player.component.ts
import {AfterViewInit, Component, ElementRef, EventEmitter, Input, OnInit, Output, ViewChild} from '@angular/core';
import {IonSelect, ToastController, Gesture, GestureController} from '@ionic/angular';
import {LibraryService} from '../../services/library.service';

@Component({
  selector: 'video-player',
  templateUrl: './video-player.component.html',
  styleUrls: ['./video-player.component.scss'],
})
export class VideoPlayerComponent implements OnInit, AfterViewInit {

    @ViewChild('video', {static: true}) videoRef: ElementRef;
    @ViewChild('tracks', {static: false}) trackSelectRef: IonSelect;
    @ViewChild('timelineProgress', {static: false}) timelineProgress: ElementRef;
    @ViewChild('timelineCursor', {static: false}) timelineCursorRef: ElementRef;

    @Input() src: string;
    @Input() poster: string;
    @Input() subtitles: string;
    @Input() title: string;
    @Input() controls: {
        show?: boolean,
        timeline?: boolean,
        subtitles?: boolean,
        playbutton?: boolean,
        fullscreen?: boolean,
        overlay?: boolean
    };

    @Output() timelineDragging = new EventEmitter<string>();

    defaultControls = {
        show: true,
        timeline: true,
        playbutton: true,
        fullscreen: true,
        subtitles: true
    };

    video: HTMLVideoElement;
    hasPlayed = false;
    playing = false;
    trackSelected = 'none';

    progress = 0;

    constructor(
        public libraryService: LibraryService,
        public toastController: ToastController,
        private gestureCtrl: GestureController
    ) {}

    ngOnInit() {
        this.controls = Object.assign(this.defaultControls, this.controls);
        this.video = this.videoRef.nativeElement;
        this.video.addEventListener('play', (event) => {
            this.hasPlayed = true;
            this.playing = true;
        });
        this.video.addEventListener('pause', (event) => {
            this.playing = false;
        });
        this.video.addEventListener('timeupdate', (event) => {
            this.progress = this.video.currentTime / this.video.duration * 100;
        });
        this.video.addEventListener('fullscreenchange', () => {
            if (document.fullscreenElement) {
                this.video.setAttribute('controls', 'true');
            } else {
                this.video.removeAttribute('controls');
            }
        });
        this.video.textTracks.addEventListener('change', (event) => {
            this.trackSelected = 'none';

            for (const track of event.currentTarget as unknown as any[]) {
                if (track.mode === 'showing') {
                    this.trackSelected = track.language;
                }
            }
        });
    }

    ngAfterViewInit() {
        let startCursorPos;
        let timelinePos;
        const gesture: Gesture = this.gestureCtrl.create({
            el: this.timelineCursorRef.nativeElement,
            threshold: 0,
            gestureName: 'my-gesture',
            passive: false,
            gesturePriority: 10,
            onStart: () => {
                startCursorPos = this.timelineCursorRef.nativeElement.getBoundingClientRect();
                timelinePos = this.timelineCursorRef.nativeElement.parentNode.getBoundingClientRect();
                this.timelineDragging.emit('dragstart');
            },
            onEnd: () => {
                this.timelineDragging.emit('dragend');
            },
            onMove: (ev) => {
                const newX = Math.min(Math.max(startCursorPos.left - timelinePos.left + ev.deltaX, 0), timelinePos.width);
                const progress = newX / timelinePos.width;
                this.hasPlayed = true;
                this.timelineProgress.nativeElement.style.width = (progress * 100) + '%';
                this.timelineCursorRef.nativeElement.style.left = (progress * 100) + '%';
                this.video.currentTime = Math.round(progress * this.video.duration);
            }
        }, true);

        gesture.enable(true);
    }

    play() {
        if (this.video.paused) {
            this.video.play();
        } else {
            this.video.pause();
        }
    }

    fullscreen(event) {
        event.preventDefault();
        event.stopPropagation();
        if (typeof this.video.requestFullscreen === 'function') {
            this.video.requestFullscreen();
        } else if (typeof this.video.webkitEnterFullscreen === 'function') {
            this.video.webkitEnterFullscreen();
        } else {
            this.presentToast('Fullscreen not supported on your phone');
        }
    }

    seek(event) {
        event.preventDefault();
        event.stopPropagation();
        const timeline = event.target.closest('.video-timeline');
        const rect = timeline.getBoundingClientRect();
        const progress = (event.clientX - rect.left) / rect.width;
        this.video.currentTime = Math.round(progress * this.video.duration);
    }

    captions() {
        this.trackSelectRef.open();
    }

    changeSubtitles($event) {
        if ($event.detail.value === 'none') {
            for (const track of this.video.textTracks as unknown as any[]) {
                track.mode = 'disabled';
            }
        } else {
            for (const track of this.video.textTracks as unknown as any[]) {
                if (track.language === $event.detail.value) {
                    track.mode = 'showing';
                } else {
                    track.mode = 'disabled';
                }
            }
        }
    }

    async presentToast(text) {
        const toast = await this.toastController.create({
            position: 'top',
            message: text,
            duration: 2000
        });
        toast.present();
    }
}

<div class="video-player" *ngIf="!isAndroid">
  <div aria-hidden="true" class="video-container" [ngClass]="{'playing':playing}" (click)="play()">
    <video *ngIf="src" #video disablePictureInPicture playsinline preload="metadata"
           [src]="src | safe: 'url': epocService.rootFolder">
      <ng-container *ngFor="let sub of subtitles">
        <track kind="subtitles" [label]="sub.label" [srclang]="sub.lang"
               [src]="sub.src | safe: 'url': epocService.rootFolder">
      </ng-container>
    </video>
    <div class="poster" *ngIf="!hasPlayed">
      <h4 class="title">{{title}}</h4>
      <img [src]="poster | safe: 'url': epocService.rootFolder" *ngIf="poster"/>
    </div>
    <ng-container *ngIf="src">
      <div class="video-play-overlay">
        <ion-icon src="assets/icon/play.svg"></ion-icon>
      </div>
      <div class="video-timeline" (click)="seek($event)" [style.display]="controls.timeline ? 'block':'none'">
        <div class="video-timeline-progress" [style.width]="progress +'%'" #timelineProgress></div>
        <div class="video-timeline-cursor" [style.left]="progress +'%'" #timelineCursor></div>
      </div>
      <div class="video-overlay-controls">
        <ion-icon name="scan-outline" (click)="fullscreen($event)" *ngIf="controls.overlay"></ion-icon>
      </div>
    </ng-container>
  </div>

  <ng-container *ngIf="src && controls.show">
    <ion-item class="hidden-select" *ngIf="controls.subtitles && subtitles && subtitles.length >0">
      <ion-label>Sous-titres</ion-label>
      <ion-select #tracks [value]="trackSelected" (ionChange)='changeSubtitles($event)'>
        <ion-select-option value="none">Aucun</ion-select-option>
        <ion-select-option [value]="sub.lang" *ngFor="let sub of subtitles">{{sub.label}}</ion-select-option>
      </ion-select>
    </ion-item>

    <div class="video-actions">
      <div class="video-actions-left" *ngIf="controls.subtitles">
        <button class="video-action" (click)="captions()" >
          <ion-icon name="logo-closed-captioning"></ion-icon>
        </button>
      </div>
      <div class="video-actions-center" *ngIf="controls.playbutton">
        <button class="video-action" aria-label="-10s" (click)="jump(-10)">-10</button>
        <button class="video-action" aria-label="Lancer la lecture" (click)="play()">
          <ion-icon [name]="playing ? 'pause':'play'"></ion-icon>
        </button>
        <button class="video-action" aria-label="-10s" (click)="jump(10)">+10</button>
      </div>
      <div class="video-actions-right" *ngIf="controls.fullscreen">
        <button class="video-action" aria-label="Plein écran" (click)="fullscreen($event)">
          <ion-icon  name="expand"></ion-icon>
        </button>
      </div>
    </div>
  </ng-container>
</div>

<div class="video-player" *ngIf="isAndroid">
  <div [id]="id"></div>
  <div class="video-container" (click)="playAndroid()">
    <div class="poster">
      <h4 class="title">{{title}}</h4>
      <img [src]="poster | safe: 'url': epocService.rootFolder" *ngIf="poster"/>
    </div>
    <div class="video-play-overlay" *ngIf="src">
      <ion-icon src="assets/icon/play.svg" *ngIf="!playing"></ion-icon>
      <ion-spinner *ngIf="playing"></ion-spinner>
    </div>
  </div>
</div>

// src/components/VideoPlayer.vue
<script setup lang="ts">
import { IonIcon, IonSelect, IonSelectOption, IonItem, IonLabel, toastController, createGesture } from '@ionic/vue';
import { ref, onMounted, onUnmounted, PropType } from 'vue';
import { useVideoPlayerStore } from '@/stores/videoPlayerStore';

const props = defineProps({
  src: String,
  poster: String,
  subtitles: {
    type: Array as PropType<{ label: string; lang: string; src: string }[]>,
    default: () => [],
  },
  title: String,
  controls: {
    type: Object as PropType<{
      show?: boolean;
      timeline?: boolean;
      subtitles?: boolean;
      playbutton?: boolean;
      fullscreen?: boolean;
      overlay?: boolean;
    }>,
    default: () => ({
      show: true,
      timeline: true,
      playbutton: true,
      fullscreen: true,
      subtitles: true,
    }),
  },
});

// Store Pinia
const videoPlayerStore = useVideoPlayerStore();

// Générer un ID unique pour ce lecteur
const playerId = `video-player-${Math.random().toString(36).substring(2, 9)}`;

// Références
const videoRef = ref<HTMLVideoElement | null>(null);
const trackSelectRef = ref<typeof IonSelect | null>(null);
const timelineProgress = ref<HTMLElement | null>(null);
const timelineCursorRef = ref<HTMLElement | null>(null);

// État local
const hasPlayed = ref(false);
const playing = ref(false);
const trackSelected = ref('none');
const progress = ref(0);
const video = ref<HTMLVideoElement | null>(null);

// Méthodes
const play = () => {
  if (!video.value) return;
  if (video.value.paused) {
    video.value.play();
  } else {
    video.value.pause();
  }
};

const jump = (delta: number) => {
  if (!video.value) return;
  video.value.currentTime += delta;
  video.value.play();
};

const fullscreen = (event: Event) => {
  event.preventDefault();
  event.stopPropagation();
  if (!video.value) return;
  if (typeof video.value.requestFullscreen === 'function') {
    video.value.requestFullscreen();
  } else if (typeof (video.value as any).webkitEnterFullscreen === 'function') {
    (video.value as any).webkitEnterFullscreen();
  } else {
    presentToast('Fullscreen not supported on your phone');
  }
};

const seek = (event: MouseEvent) => {
  event.preventDefault();
  event.stopPropagation();
  if (!video.value) return;
  const timeline = (event.target as HTMLElement).closest('.video-timeline');
  if (!timeline) return;
  const rect = timeline.getBoundingClientRect();
  const progressValue = (event.clientX - rect.left) / rect.width;
  video.value.currentTime = Math.round(progressValue * video.value.duration);
};

const captions = () => {
  if (trackSelectRef.value) {
    trackSelectRef.value?.open();
  }
};

const changeSubtitles = (event: CustomEvent) => {
  if (!video.value) return;
  const value = event.detail.value;
  for (const track of Array.from(video.value.textTracks)) {
    if (value === 'none') {
      track.mode = 'disabled';
    } else if (track.language === value) {
      track.mode = 'showing';
    } else {
      track.mode = 'disabled';
    }
  }
  trackSelected.value = value;
};

const presentToast = async (text: string) => {
  const toast = await toastController.create({
    position: 'top',
    message: text,
    duration: 2000,
  });
  toast.present();
};

// Cycle de vie
onMounted(() => {
  if (!videoRef.value) return;
  video.value = videoRef.value;

  video.value.addEventListener('error', () => {
    presentToast('Error loading video');
  });

  video.value.addEventListener('loadedmetadata', () => {
    videoPlayerStore.registerPlayer(playerId, video.value?.duration || 0);
  });

  video.value.addEventListener('play', () => {
    hasPlayed.value = true;
    playing.value = true;
    videoPlayerStore.setPlayerState(playerId, { isPlaying: true, currentTime: video.value?.currentTime || 0 });
  });

  video.value.addEventListener('pause', () => {
    playing.value = false;
    videoPlayerStore.setPlayerState(playerId, { isPlaying: false, currentTime: video.value?.currentTime || 0 });
  });

  video.value.addEventListener('timeupdate', () => {
    if (!video.value) return;
    progress.value = (video.value.currentTime / video.value.duration) * 100;
    videoPlayerStore.setPlayerState(playerId, { isPlaying: !video.value.paused, currentTime: video.value.currentTime });
  });

  video.value.addEventListener('fullscreenchange', () => {
    if (!video.value) return;
    if (document.fullscreenElement) {
      video.value.setAttribute('controls', 'true');
    } else {
      video.value.removeAttribute('controls');
    }
  });

  video.value.textTracks.addEventListener('change', () => {
    if (!video.value) return;
    trackSelected.value = 'none';
    for (const track of Array.from(video.value.textTracks)) {
      if (track.mode === 'showing') {
        trackSelected.value = track.language;
      }
    }
  });

  // Gestion du geste sur la timeline
  if (!timelineCursorRef.value) return;
  let startCursorPos: DOMRect | null = null;
  let timelinePos: DOMRect | null = null;

  const gesture = createGesture({
    el: timelineCursorRef.value,
    threshold: 0,
    gestureName: 'my-gesture',
    onStart: () => {
      if (!timelineCursorRef.value) return;
      startCursorPos = timelineCursorRef.value.getBoundingClientRect();
      timelinePos = timelineCursorRef.value.parentElement?.getBoundingClientRect() || null;
    },
    onEnd: () => {},
    onMove: (ev) => {
      if (!startCursorPos || !timelinePos || !video.value || !timelineProgress.value || !timelineCursorRef.value) return;
      const newX = Math.min(
          Math.max(startCursorPos.left - timelinePos.left + ev.deltaX, 0),
          timelinePos.width
      );
      const progressValue = newX / timelinePos.width;
      hasPlayed.value = true;
      timelineProgress.value.style.width = progressValue * 100 + '%';
      timelineCursorRef.value.style.left = progressValue * 100 + '%';
      video.value.currentTime = Math.round(progressValue * video.value.duration);
    },
  });
  gesture.enable(true);
});

// Nettoyage
onUnmounted(() => {
  videoPlayerStore.unregisterPlayer(playerId);
});
</script>

<template>
  <div class="video-player">
    <div
        aria-hidden="true"
        class="video-container"
        :class="{ playing }"
        @click="play"
    >
      <video
          v-if="src"
          ref="videoRef"
          disablePictureInPicture
          playsinline
          preload="metadata"
          :src="src"
      >
        <track
            v-for="sub in subtitles"
            :key="sub.lang"
            kind="subtitles"
            :label="sub.label"
            :srclang="sub.lang"
            :src="sub.src"
        />
      </video>
      <div v-if="!hasPlayed" class="poster">
        <h4 class="title">{{ title }}</h4>
        <img v-if="poster" :src="poster" />
      </div>
      <div v-if="src">
        <div class="video-play-overlay">
          <ion-icon src="/assets/icon/play.svg"></ion-icon>
        </div>
        <div
            v-if="controls.timeline"
            class="video-timeline"
            @click="seek"
        >
          <div
              class="video-timeline-progress"
              :style="{ width: progress + '%' }"
              ref="timelineProgress"
          ></div>
          <div
              class="video-timeline-cursor"
              :style="{ left: progress + '%' }"
              ref="timelineCursor"
          ></div>
        </div>
        <div v-if="controls.overlay" class="video-overlay-controls">
          <ion-icon name="scan-outline" @click="fullscreen"></ion-icon>
        </div>
      </div>
    </div>
    <div v-if="src && controls.show" class="video-actions">
      <div class="video-actions-left">
        <button
            v-if="controls.subtitles && subtitles && subtitles.length > 0"
            class="video-action"
            @click="captions"
        >
          <ion-icon name="logo-closed-captioning"></ion-icon>
        </button>
      </div>
      <div v-if="controls.playbutton" class="video-actions-center">
        <button class="video-action" aria-label="-10s" @click="jump(-10)">
          -10
        </button>
        <button class="video-action" aria-label="Lancer la lecture" @click="play">
          <ion-icon :name="playing ? 'pause' : 'play'"></ion-icon>
        </button>
        <button class="video-action" aria-label="+10s" @click="jump(10)">
          +10
        </button>
      </div>
      <div v-if="controls.fullscreen" class="video-actions-right">
        <button class="video-action" aria-label="Plein écran" @click="fullscreen">
          <ion-icon name="expand"></ion-icon>
        </button>
      </div>
    </div>
    <ion-item
        v-if="controls.subtitles && subtitles && subtitles.length > 0"
        class="hidden-select"
    >
      <ion-label>Sous-titres</ion-label>
      <ion-select
          ref="trackSelectRef"
          :value="trackSelected"
          @ionChange="changeSubtitles"
      >
        <ion-select-option value="none">Aucun</ion-select-option>
        <ion-select-option
            v-for="sub in subtitles"
            :key="sub.lang"
            :value="sub.lang"
        >
          {{ sub.label }}
        </ion-select-option>
      </ion-select>
    </ion-item>
  </div>
</template>

<style scoped lang="scss">
.video-player {
  .video-container {
    position: relative;
    min-height: 210px;
  }
  .video-container .poster {
    display: flex;
    align-items: center;
    justify-content: center;
    position: absolute;
    width: 100%;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    background: var(--ion-color-inria-blue);
  }
  .video-container .poster .title {
    padding: 20px;
    color: white;
    text-align: center;
  }
  .video-container .poster img {
    position: absolute;
    width: 100%;
    height: auto;
    object-fit: cover;
  }
  .video-container .video-play-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    cursor: pointer;
    background: rgba(var(--ion-color-inria-blue-rgb), 0.2);
    z-index: 1;
    font-size: 4rem;
  }
  .video-container .video-play-overlay ion-icon {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  .video-container.playing .video-play-overlay {
    opacity: 0;
  }
  .video-container .video-overlay-controls {
    position: absolute;
    bottom: 0;
    right: 0;
    padding: 5px;
    z-index: 2;
  }
  .video-container .video-overlay-controls ion-icon {
    font-size: 20px;
    line-height: 1;
    color: white;
    cursor: pointer;
    filter: drop-shadow(0 0 2px var(--ion-color-inria-blue));
  }
  @keyframes fadeOut {
    from {
      opacity: 1;
    }
    to {
      opacity: 0;
    }
  }
  video {
    display: block;
    width: 100%;
    height: auto;
    margin: 0;
    background: none;
  }
  .video-actions {
    display: flex;
    font-size: 25px;
    justify-content: space-between;
    padding: 16px;
  }
  .video-actions .video-action {
    position: relative;
    display: block;
    width: 30px;
    height: 30px;
    margin: 0;
    padding: 0;
    border-radius: 5px;
    background: var(--ion-color-contrast);
    color: var(--ion-color-inria);
    text-align: center;
    line-height: 35px;
  }
  .video-actions .video-action ion-icon {
    position: absolute;
    display: inline-block;
    top: 50%;
    left: 50%;
    width: 50%;
    height: 50%;
    transform: translate(-50%, -50%);
  }
  .video-actions-left {
    display: flex;
    width: 30px;
  }
  .video-actions-center {
    display: flex;
    text-align: center;
  }
  .video-actions-center .video-action {
    margin: 0 5px;
  }
  .video-actions-right {
    display: flex;
    width: 30px;
  }
  .video-timeline {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 10px;
    z-index: 2;
  }
  .video-timeline:before {
    content: '';
    display: block;
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 3px;
    background: rgba(var(--ion-color-inria-light-rgb), 0.5);
  }
  .video-timeline-progress {
    position: absolute;
    bottom: 0;
    left: 0;
    height: 3px;
    background: var(--ion-color-inria);
  }
  .video-timeline-cursor {
    position: absolute;
    top: calc(50% + 3.5px);
    padding: 8px;
    z-index: 10;
    transform: translate(-50%, -50%);
    transform-origin: center center;
    opacity: 0;
  }
  .video-timeline-cursor:before {
    content: '';
    display: block;
    width: 13px;
    height: 13px;
    border-radius: 50%;
    background: white;
    border: 1px solid var(--ion-color-light-shade);
  }
}
.hidden-select {
  display: none;
}
</style>
