// src/views/epoc/content/SimpleQuestion.vue
<script setup lang="ts">
import {ref} from 'vue';
import {Zip} from '@epoc/capacitor-zip';
import {Directory, Encoding, Filesystem} from '@capacitor/filesystem';
import {FileTransfer} from '@capacitor/file-transfer';
import {useConvertFileSrc} from '@/composables/useConvertFileSrc';
import { useEpocStore } from '@/stores/epocStore';

  const epocStore = useEpocStore()
  // const readonlyTracker = Matomo TODO
 @Input() content: Content;
    @Input() question: Question;
    @Input() epocId: string;
    @Output() dragging = new EventEmitter<string>();

    @ViewChild(CommonQuestionComponent, { static: false })
    private questionComponent!: CommonQuestionComponent;

    reading: Reading;
    const userAssessment = ref();
    const questionAnswered = ref(false);
    const disableCheck = ref(true);
    userResponses = [];


    onBeforeMount(async () => {
      const id = route.params.id.toString();
      await epocStore.getEpocById(id);
      this.readingStore.readings$.subscribe(readings => {
            if (readings) {
                this.reading = readings.find(item => item.epocId === this.epocId);
                this.userAssessment = this.reading.assessments.find(a => a.id === this.content.id);
            }
        });
    });

  const checkAnswer = (event) => {
        event.preventDefault();
        event.stopPropagation();
        const userSucceeded = this.epocService.isUserResponsesCorrect(this.question.correctResponse, this.userResponses);
        const score = userSucceeded ? +this.question.score : 0;
        this.readingStore.saveResponses(this.epocId, this.content.id, score, this.userResponses);
        this.questionComponent.showCorrection();
        this.tracker.trackEvent('Assessments', 'Answered simple question', `Answered ${this.epocId} ${this.content.id}`, score);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'attempted', true);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'scored', score);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'passed', userSucceeded);
    }

  const onQuestionAnswered = (event) => {
        questionAnswered.value = event;
    }

  const onDrag = (value) => {
        dragging.emit(value);
    }

  const onUserHasResponded = (userResponses) => {
        userResponses.value = userResponses;
        disableCheck.value = false;
    }
</script>

<template>
  <common-question icon="help-circle-outline" :title="content.title" :subtitle="content.subtitle" :contentId="content.id"
                 :epocId="epocId" :question="question" :userAssessment="userAssessment"
                 :questionAnswered="onQuestionAnswered($event)"
                 :dragging="onDrag($event)" :userHasResponded="onUserHasResponded($event)">
  <ion-button v-if="!questionAnswered && question.responses.length > 0" :disabled="disableCheck" expand="block" size="large" color="inria" v-on:click="checkAnswer($event)">
    <span>{{$t('QUESTION.SIMPLE_QUESTION.VALIDATE')}}</span>
  </ion-button>
  <ion-button v-if="question.responses.length <= 0" expand="block" size="large" color="outline-button" fill="outline" v-on:click="checkAnswer($event)">
    <span>{{$t('QUESTION.SIMPLE_QUESTION.FINISH')}}</span>
  </ion-button>
</common-question>

</template>

<style>
@import "../../../colors";

.video-player{
  .video-container{
    position: relative;
    min-height: 210px;

    .poster{
      display: flex;
      align-items: center;
      justify-content: center;
      position: absolute;
      width:100%;
      top:0;
      left:0;
      bottom:0;
      right:0;
      background: var(--ion-color-inria-blue);

      .title{
        padding: 20px;
        color: white;
        text-align: center;
      }

      img{
        position: absolute;
        width:100%;
        height: auto;
        object-fit: cover;
      }
    }

    .video-play-overlay{
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      cursor: pointer;
      background: rgba(var(--ion-color-inria-blue-rgb), 0.2);
      z-index: 1;
      font-size: 4rem;

      ion-icon, ion-spinner{
        position: absolute;
        top:50%;
        left:50%;
        transform: translate(-50%, -50%);
      }
    }

    &.playing {
      .video-play-overlay{
        opacity: 0;
      }
    }

    .video-overlay-controls{
      position: absolute;
      bottom: 0;
      right:0;
      padding: 5px;
      z-index: 2;

      ion-icon{
        font-size: 20px;
        line-height: 1;
        color:white;
        cursor: pointer;
        filter: drop-shadow(0 0 2px var(--ion-color-inria-blue));
      }
    }

    @keyframes fadeOut {
      from {
        opacity: 1;
      }
      to {
        opacity: 0;
      }
    }
  }

  video{
    display: block;
    width: 100%;
    height: auto;
    margin:0;
    background:none;
  }

  .video-actions{
    display: flex;
    font-size: 25px;
    justify-content: space-between;
    padding: 16px;

    .video-action {
      position: relative;
      display: block;
      width:30px;
      height:30px;
      margin: 0;
      padding: 0;
      border-radius: 5px;
      background: var(--ion-color-contrast);
      color: var(--ion-color-inria);
      text-align: center;
      line-height: 35px;

      ion-icon {
        position: absolute;
        display: inline-block;
        top: 50%;
        left: 50%;
        width: 50%;
        height: 50%;
        transform: translate(-50%, -50%);
      }
    }

    &-left{
      display: flex;
      width: 30px;
    }
    &-center{
      display: flex;
      text-align: center;

      .video-action{
        margin: 0 5px;
      }
    }
    &-right{
      display: flex;
      width: 30px;
    }
  }

  .video-timeline{
    position: absolute;
    bottom: 0;
    left:0;
    width:100%;
    height: 10px;
    z-index: 2;


    &:before{
      content:'';
      display: block;
      position: absolute;
      bottom: 0;
      left:0;
      width:100%;
      height: 3px;
      background: rgba(var(--ion-color-inria-light-rgb), 0.5);
    }

    &-progress{
      position: absolute;
      bottom: 0;
      left:0;
      height: 3px;
      background: var(--ion-color-inria);
    }

    &-cursor{
      position: absolute;
      top: calc(50% + 3.5px);
      padding: 8px;
      z-index: 10;
      transform: translate(-50%, -50%);
      transform-origin: center center;
      opacity: 0;

      &:before{
        content:'';
        display: block;
        width: 13px;
        height:13px;
        border-radius: 50%;
        background: white;
        border: 1px solid var(--ion-color-light-shade);
      }
    }
  }
}

.hidden-select{
  display: none;
}

</style>

// src/app/pages/epoc/player/contents/simple-question/simple-question.component.ts
import {Component, EventEmitter, Input, OnInit, Output, ViewChild} from '@angular/core';
import {Question, SimpleQuestion} from 'src/app/classes/contents/assessment';
import {Reading} from 'src/app/classes/reading';
import {Content} from 'src/app/classes/contents/content';
import {CommonQuestionComponent} from 'src/app/components/questions/common-question/common-question.component';
import {ReadingStoreService} from 'src/app/services/reading-store.service';
import {EpocService} from 'src/app/services/epoc.service';
import {MatomoTracker} from '@ngx-matomo/tracker';

@Component({
    selector: 'simple-question',
    templateUrl: './simple-question.component.html',
    styleUrls: ['./simple-question.component.scss'],
})
export class SimpleQuestionComponent implements OnInit {
    @Input() content: Content;
    @Input() question: Question;
    @Input() epocId: string;
    @Output() dragging = new EventEmitter<string>();

    @ViewChild(CommonQuestionComponent, { static: false })
    private questionComponent!: CommonQuestionComponent;

    reading: Reading;
    userAssessment;
    questionAnswered = false;
    disableCheck = true;
    userResponses = [];

    constructor(
        private readingStore: ReadingStoreService,
        private epocService: EpocService,
        private readonly tracker: MatomoTracker
    ) {}

    ngOnInit() {
        this.readingStore.readings$.subscribe(readings => {
            if (readings) {
                this.reading = readings.find(item => item.epocId === this.epocId);
                this.userAssessment = this.reading.assessments.find(a => a.id === this.content.id);
            }
        });
    }

    checkAnswer(event) {
        event.preventDefault();
        event.stopPropagation();
        const userSucceeded = this.epocService.isUserResponsesCorrect(this.question.correctResponse, this.userResponses);
        const score = userSucceeded ? +this.question.score : 0;
        this.readingStore.saveResponses(this.epocId, this.content.id, score, this.userResponses);
        this.questionComponent.showCorrection();
        this.tracker.trackEvent('Assessments', 'Answered simple question', `Answered ${this.epocId} ${this.content.id}`, score);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'attempted', true);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'scored', score);
        this.readingStore.saveStatement(this.epocId, 'questions', (this.content as SimpleQuestion).question, 'passed', userSucceeded);
    }

    onQuestionAnswered (event) {
        this.questionAnswered = event;
    }

    onDrag(value){
        this.dragging.emit(value);
    }

    onUserHasResponded (userResponses) {
        this.userResponses = userResponses;
        this.disableCheck = false;
    }
}

<flip-card disabled="true">
    <div front>
        <div class="title-container">
            <div class="title-icon">
                <ion-icon name="help-circle-outline"></ion-icon>
            </div>
            <h5 class="subtitle">{{content.subtitle}}</h5>
            <h4 class="title">{{content.title}} {{+question.score ? '(' + question.score + 'pts)' : ''}}</h4>
        </div>

        <div class="statement ion-text-center">
            <div *ngIf="question.statement">{{question.statement}}</div>
            <b>{{question.label}}</b>
        </div>
        <p class="nbCorrect" *ngIf="correctionState">{{!solutionShown ? +question.score ? everythingIsCorrect ? question.score + 'pts' : '0pts' : 'Vos réponses' : 'Solution'}}</p>

        <ng-container *ngIf="question.responses.length === 0">
            <ion-radio-group [value]="answer">
                <ion-item [lines]="'none'" *ngFor="let response of question.responses"
                          (click)="selectAnswer(response.value)">
                    <ion-radio mode="md" slot="start" [value]="response.value"
                               [disabled]="disabled"></ion-radio>
                    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
                </ion-item>
            </ion-radio-group>
            <button (click)="checkAnswer($event)"
                    [ngClass]="disabled ? 'disabled':''">{{epoc.parameters.openQuestionButton ? epoc.parameters.openQuestionButton : 'Valider'}}</button>
        </ng-container>

        <ng-container *ngIf="question.type === 'choice' && question.responses.length !== 0">
            <ion-radio-group [value]="!solutionShown ? answer : question.correctResponse[0]">
                <ion-item [lines]="'none'" *ngFor="let response of question.responses"
                          (click)="selectAnswer(response.value)"
                          [ngClass]="{
           'correct': (solutionShown && response.value === question.correctResponse[0])
           || (answer === question.correctResponse[0] && answer === response.value && correctionState && !solutionShown),
           'incorrect': correctionState
           && !solutionShown
           && (answer !== question.correctResponse[0] && answer === response.value)
           }">
                    <ion-radio mode="md" slot="start" [value]="response.value"
                               [disabled]="disabled"></ion-radio>
                    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
                </ion-item>
            </ion-radio-group>
        </ng-container>

        <ng-container *ngIf="question.type === 'multiple-choice' && question.responses.length !== 0">
            <ion-list>
                <ion-item [lines]="'none'" *ngFor="let response of question.responses"
                          [ngClass]="{
        'correct': correctionState && question.correctResponse.includes(response.value) && (solutionShown || answer.includes(response.value)),
        'incorrect': correctionState && answer.includes(response.value) && !question.correctResponse.includes(response.value)}">
                    <ion-checkbox mode="md" slot="start" [value]="!correctionState && response.value"
                                  (ionChange)="selectAnswerMultiple($event)"
                                  [disabled]="disabled"
                                  [checked]="solutionShown ? question.correctResponse.includes(response.value) : answer.includes(response.value)"
                    ></ion-checkbox>
                    <ion-label class="ion-text-wrap">{{response.label}}</ion-label>
                </ion-item>
            </ion-list>
        </ng-container>

        <div class="buttons">
            <ion-button class="toggleSolution" (click)="toggleSolution($event)" *ngIf="this.explanationShown"
                        [disabled]="this.flipped || everythingIsCorrect"
                        [ngClass]="this.flipped || everythingIsCorrect ? 'usrSelect': ''">
                <div class="answerState" *ngIf="!solutionShown">
                    <ion-icon name="bulb-outline"></ion-icon>
                    SOLUTION
                </div>
                <div class="solutionState" *ngIf="solutionShown">
                    VOS REPONSES
                </div>
            </ion-button>
            <ion-button class="explication" *ngIf="this.explanationShown" (click)="flip()">
                <div class="explanationFront" *ngIf="!this.flipped">
                    <ion-icon name="eye-outline"></ion-icon>
                    EXPLICATION
                </div>
                <div class="explanationBack" *ngIf="this.flipped">
                    <ion-icon name="eye-off-outline"></ion-icon>
                    EXPLICATION
                </div>
            </ion-button>
        </div>
        <ion-button class="check-answer" [disabled]="correctionState || !answer" (click)="checkAnswer($event); explanationShown = true"
                    *ngIf="!explanationShown">Valider
        </ion-button>
    </div>
    <html-content [html]="question.explanation" (click)="flip()" back></html-content>
</flip-card>
