// src-angular/app/pages/epoc/score/score.page.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute, ParamMap, Router} from '@angular/router';
import {switchMap} from 'rxjs/operators';
import {ReadingStoreService} from 'src/app/services/reading-store.service';
import {combineLatest, Observable} from 'rxjs';
import {Badge, Epoc} from 'src/app/classes/epoc';
import {AlertController, LoadingController} from '@ionic/angular';
import {Reading} from 'src/app/classes/reading';
import {Assessment, SimpleQuestion} from 'src/app/classes/contents/assessment';
import {jsPDF} from 'jspdf';
import {User} from 'src/app/classes/user';
import {AuthService} from 'src/app/services/auth.service';
import {Capacitor} from '@capacitor/core';
import {Directory, Filesystem} from '@capacitor/filesystem';
import {FileOpener, FileOpenerOptions} from '@capacitor-community/file-opener';
import {EpocService} from 'src/app/services/epoc.service';
import {MatomoTracker} from '@ngx-matomo/tracker';
import {SettingsStoreService} from 'src/app/services/settings-store.service';
import {Settings} from 'src/app/classes/settings';
import {TranslateService} from '@ngx-translate/core';
import {uid} from '@epoc/epoc-types/dist/v1';

const colors = {
    darkblue: '#384257',
    blue: '#6477A0',
    orange: '#FFA029',
    lightblue: '#edf3f8'
};

@Component({
    selector: 'app-epoc-score',
    templateUrl: 'score.page.html',
    styleUrls: ['score.page.scss']
})
export class EpocScorePage implements OnInit {

    epoc$: Observable<Epoc>;
    epoc: Epoc;
    reading: Reading;
    assessments: (Assessment|SimpleQuestion)[];

    assessmentData;

    user: User;
    loading: boolean;
    certificateUnlocked = false;

    settings: Settings;

    badgeMode = false;
    unlockedBadges: uid[] = [];
    badgeModal: Badge = null;
    showBadgeModal = false;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        public epocService: EpocService,
        private readingStore: ReadingStoreService,
        private auth: AuthService,
        public alertController: AlertController,
        public loadingController: LoadingController,
        private readonly tracker: MatomoTracker,
        private settingsStore: SettingsStoreService,
        public translate: TranslateService
    ) {}

    ngOnInit() {
        this.epoc$ = this.route.paramMap.pipe(
            switchMap((params: ParamMap) =>
                this.epocService.getEpoc(params.get('id')))
        );

        this.epoc$.subscribe(epoc => {
            this.epoc = epoc;
            this.assessments = epoc.assessments;
            if (Object.keys(this.epoc.badges).length > 0) {
                this.badgeMode = true;
            }
        });

        this.auth.getUser().subscribe(user => {
            this.user = user;
        });

        this.settingsStore.settings$.subscribe(settings => {
            if (settings) {
                this.settings = settings;
            }
        });
    }

    ionViewDidEnter() {
        combineLatest([this.epoc$, this.readingStore.readings$]).subscribe(([epoc, readings]) => {
            if (epoc && readings) {
                this.reading = readings.find(item => item.epocId === this.route.snapshot.paramMap.get('id'));
                if (!this.reading) this.readingStore.addReading(this.epoc.id);
                if (this.badgeMode) {
                    this.unlockedBadges = this.reading.badges;
                    this.certificateUnlocked = epoc.certificateBadgeCount <= this.unlockedBadges.length
                } else {
                    this.setAssessmentsData();
                }
            }
        });
    }

    setAssessmentsData() {
        this.assessmentData = {
            successScore: 0,
            attemptedScore: 0,
            todoScore: 0,
            totalUserScore: 0,
            totalScore: 0
        };

        this.assessments.forEach((assessment) => {
            const userAssessment = this.reading?.assessments.find(a => assessment.id === a.id);
            const scoreTotal = this.epocService.calcScoreTotal(this.epoc, assessment.questions);

            assessment.score = this.getScore(assessment);
            assessment.scoreTotal = this.getScoreTotal(assessment);

            if (userAssessment && userAssessment.score > 0) {
                this.assessmentData.totalUserScore += userAssessment.score;
                this.assessmentData.successScore += userAssessment.score;

                if (userAssessment.score < scoreTotal) {
                    this.assessmentData.attemptedScore += scoreTotal - userAssessment.score;
                }
            } else {
                this.assessmentData.todoScore += scoreTotal;
            }
            this.assessmentData.totalScore += scoreTotal;
        });

        this.certificateUnlocked = this.assessmentData.totalUserScore >= this.epoc.certificateScore;
    }

    getScore(content) {
        if (this.reading) {
            const userAssessment = this.reading.assessments.find(assessment => assessment.id === content.id);
            if (userAssessment) {
                return userAssessment.score;
            }
        }

        return null;
    }

    getScoreTotal(content) {
        return this.epocService.calcScoreTotal(this.epoc, content.questions);
    }

    async getCertificate() {
        if (!this.loading) {
            if (this.settings.devMode || this.certificateUnlocked) {
                if (!this.user) {
                    this.setUser().then();
                } else {
                    this.presentLoading().then(async () => {
                        this.downloadPdf(await this.generatePdf());
                    });
                }
            } else {
                this.presentFail(
                    this.translate.instant('PLAYER.SCORE.FAIL_MODAL.HEADER'),
                    this.translate.instant('PLAYER.SCORE.FAIL_MODAL.MSG', {score: this.epoc.certificateScore})
                );
            }
        }
    }

    async setUser(){
        const alert = await this.alertController.create({
            header: this.translate.instant('SETTINGS_PAGE.SET_USER.INFO'),
            message: this.translate.instant('SETTINGS_PAGE.SET_USER.MESSAGE'),
            inputs: [
                {
                    name: 'lastname',
                    type: 'text',
                    placeholder: this.translate.instant('SETTINGS_PAGE.SET_USER.LASTNAME_PLACEHOLDER'),
                },
                {
                    name: 'firstname',
                    type: 'text',
                    placeholder: this.translate.instant('SETTINGS_PAGE.SET_USER.FIRSTNAME_PLACEHOLDER'),
                }
            ],
            buttons: [
                {
                    text: this.translate.instant('CANCEL'),
                    role: 'cancel',
                    cssClass: 'secondary'
                }, {
                    text: this.translate.instant('CONFIRM'),
                    handler: (data) => {
                        this.user = {firstname:data.firstname, lastname: data.lastname , username: null, email: null};
                        this.auth.setUser(this.user);
                        this.presentLoading().then(async () => {
                            this.downloadPdf(await this.generatePdf());
                        });
                    }
                }
            ]
        });

        await alert.present();
    }

    svgToPNG (url, width) : Promise<string> {
        return new Promise(resolve => {
            const img = document.createElement('img');
            img.onload = () => {
                document.body.appendChild(img);
                const canvas = document.createElement('canvas');
                const ratio = (img.clientWidth / img.clientHeight) || 1;
                document.body.removeChild(img);
                canvas.width = width;
                canvas.height = width / ratio;
                const ctx = canvas.getContext('2d');
                ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                try {
                    const data = canvas.toDataURL('image/png');
                    resolve(data);
                } catch (e) {
                    resolve(null);
                }
            };
            img.onerror = () => {
                resolve(null);
            };
            img.src = url;
        });
    }


    async insertBadges(doc: jsPDF, posY: number): Promise<number> {
        const badges = Object.entries(this.epoc.badges);

        const w = 20;
        const h = w * 1.111;
        const size = w * 0.4;
        const offset = 25;
        const center = doc.internal.pageSize.width / 2;
        const startX = center - (badges.length*(offset/2))

        let x = startX;
        const y = posY;

        for (const [key, badge] of badges) {
            let url;
            const prefix = '/assets/icon/badge/';
            if (!badge.icon.endsWith('.svg')) {
                url = prefix + badge.icon + '.svg';
            } else {
                url = this.epocService.rootFolder + badge.icon;
            }

            if (this.unlockedBadges.includes(key)) {
                const bg = await this.svgToPNG(prefix + 'shape.svg', 500);
                doc.addImage(bg, 'PNG', x, y, w, h);
                try {
                    const icon = await this.svgToPNG(url, 500);
                    doc.addImage(icon, 'PNG', x + 6, y + 6, size, size);
                } catch (e) {
                    console.log(url)
                }
                const fg = await this.svgToPNG(prefix + 'shadow-grey.svg', 500);
                doc.addImage(fg, 'PNG', x, y, w, h);
            } else {
                const bg = await this.svgToPNG(prefix + 'locked.svg', 500);
                doc.addImage(bg, 'PNG', x, y, w, h);
            }

            doc.setFontSize(8);
            doc.text(badge.title, x+10, y+26, {align: 'center', maxWidth: 20});
            x += offset;
        }

        return y + 40;
    }

    async generatePdf(): Promise<jsPDF> {
        const password = Math.random().toString(36).substring(2, 12);
        const doc = new jsPDF({
            orientation: 'portrait',
            compress: true,
            encryption: {
                userPermissions: ['print'],
                ownerPassword: password
            }
        });
        const img = new Image();
        const centeredText = (text, y) => {
            const textWidth = doc.getStringUnitWidth(text) * doc.getFontSize() / doc.internal.scaleFactor;
            const textOffset = (doc.internal.pageSize.width - textWidth) / 2;
            doc.text(text, textOffset, y);
        };

        img.src = 'assets/img/fond-attestation.png';
        doc.addImage(img, 'PNG', 0, 0, 210, 297);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(15);
        doc.setTextColor(colors.orange);
        centeredText(this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.COMPLETION_CERTIFICATE'), 90);
        doc.setFontSize(18);
        doc.setTextColor(colors.darkblue);
        centeredText(this.epoc.title, 110);
        doc.setFillColor(colors.orange);
        doc.roundedRect(90, 120, 30, 1, 1, 1, 'F');

        let posY = 130;

        if (this.epoc.badges && Object.values(this.epoc.badges).length > 0) {
            doc.setFontSize(12);
            doc.setFont('Helvetica', 'normal');
            centeredText('Bagdes', posY);
            posY = await this.insertBadges(doc, posY+10);
        }

        doc.setFontSize(12);
        doc.setFont('Helvetica', 'normal');
        centeredText(this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.AUTHORS'), posY);
        doc.setFontSize(10);
        doc.setTextColor(colors.blue);
        posY += 10;
        const margin = 2;
        const date = new Date();
        Object.values(this.epoc.authors).forEach((author, index, array) => {
            if (index % 2 === 0) {
                if (index === array.length - 1) {
                    centeredText(author.name, posY);
                    posY += 6;
                } else {
                    const textWidth = doc.getStringUnitWidth(author.name) * doc.getFontSize() / doc.internal.scaleFactor;
                    doc.text(author.name, 104 - margin - textWidth, posY);
                }
            } else {
                doc.text(author.name, 104 + margin, posY);
                posY += 6;
            }
        });
        doc.setTextColor(colors.darkblue);
        centeredText(`${this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.EPOC_EDITION')} : ${this.epoc.edition ? this.epoc.edition : date.getFullYear()}`, posY);
        posY += 6;
        doc.setFillColor(colors.lightblue);
        doc.roundedRect(50, posY, 110, 1, 1, 1, 'F');
        posY += 10;
        doc.setFontSize(12);
        centeredText(this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.DELIVERED_TO'), posY);
        posY += 10;
        doc.setFontSize(18);
        doc.setFont('Helvetica', 'bold');
        centeredText(this.user.firstname + ' ' + this.user.lastname, posY);
        posY += 7;
        doc.setFontSize(10);
        doc.setFont('Helvetica', 'normal');
        centeredText(`${this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.DELIVERED_THE')} ${this.translate.currentLang === 'fr' ? date.toLocaleDateString('fr') : date.toLocaleDateString('en-US')}`, posY);
        const id = Math.floor(Math.random() * 10000000);
        posY += 7;
        doc.setFontSize(8);
        doc.setFont('Helvetica', 'normal');
        centeredText(`N°${id}`, posY);

        this.tracker.trackEvent('Certificate', 'Generate certificate', `Certificate ${this.epoc.id} n°${id} (${password})`);
        return doc;
    }

    downloadPdf(doc: jsPDF) {
        const fileName = `attestation-${this.epoc.id}.pdf`;

        if (Capacitor.getPlatform() === 'ios' || Capacitor.getPlatform() === 'android') {
            // Save the PDF to the device
            const output = doc.output('datauristring');
            Filesystem.writeFile({
                path: fileName,
                data: output,
                directory: Directory.Data
            }).then(() => {
                Filesystem.getUri({
                    directory: Directory.Data,
                    path: fileName
                }).then((getUriResult) => {
                    try {
                        const path = getUriResult.uri;
                        const fileOpenerOptions: FileOpenerOptions = {
                            filePath: path,
                            contentType: 'application/pdf',
                            openWithDefault: true,
                        };
                        FileOpener.open(fileOpenerOptions).then(() => {
                            this.dismissLoading();
                        }).catch(() => {
                            this.dismissLoading().then(() => {
                                this.presentFail(
                                    this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                                    this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {type: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.OPEN')}),
                                );
                            });
                        });
                    } catch (e) {
                        this.dismissLoading().then(() => {
                            this.presentFail(
                                this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                                this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {type: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.OPEN')}),
                            );
                        });
                    }
                }).catch(() => {
                    this.dismissLoading().then(() => {
                        this.presentFail(
                            this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                            this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {type: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.RECUP')}),
                        );
                    });
                });
            }).catch(() => {
                this.dismissLoading().then(() => {
                    this.presentFail(
                        this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                            this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {type: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.SAVE')}),
                    );
                });
            });
        } else {
            doc.output('dataurlnewwindow');
            this.dismissLoading();
        }
    }

    showBadgeDetail(badge: Badge) {
        this.badgeModal = badge;
        this.showBadgeModal = true;
    }

    async presentLoading() {
        this.loading = true;
        const loading = await this.loadingController.create({
            message: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.WAITING'),
        });
        await loading.present();
    }

    async dismissLoading() {
        this.loading = false;
        this.loadingController.dismiss();
    }

    async presentFail(header, message) {
        const alert = await this.alertController.create({
            header,
            message,
            buttons: [this.translate.instant('OK')]
        });

        await alert.present();
    }

    async presentSuccess() {
        const alert = await this.alertController.create({
            header: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.DOWNLOAD_FINISH'),
            message: this.translate.instant('PLAYER.SCORE.CERTIFICATE_PDF.CERTIFICATE_OBTENTION'),
            buttons: [this.translate.instant('OK')]
        });

        await alert.present();
    }
}

// src/views/epoc/ScorePage.vue
<script setup lang="ts">
import {
    IonContent,
    IonHeader,
    IonPage,
    IonToolbar,
    IonTitle,
    IonButtons,
    IonIcon,
    IonBackButton,
    IonButton,
    alertController,
    loadingController,
} from '@ionic/vue';
import { ref, reactive, onBeforeMount, computed, Ref, watch } from 'vue';
import { useEpocStore } from '@/stores/epocStore';
import ScoreProgress from '@/components/ScoreProgress.vue';
import { useRoute } from 'vue-router';
import { chevronForwardOutline, downloadOutline, starOutline } from 'ionicons/icons';
import BadgeComponent from '@/components/Badge.vue';
import type { Badge } from '@/types/epoc';
import { useI18n } from 'vue-i18n';
import { useSettingsStore } from '@/stores/settingsStore';
import { useUser } from '@/composables';
import { handleSetUser } from '@/utils/user';
import { Capacitor } from '@capacitor/core';
import { Directory, Filesystem } from '@capacitor/filesystem';
import jsPDF from 'jspdf';
import { generatePdf } from '@/utils/pdf';
import { useReadingStore } from '@/stores/readingStore';
import { storeToRefs } from 'pinia';
import type { Reading } from '@/types/reading';
import type { uid } from '@epoc/epoc-types/dist/v1';
// import { FileOpener, FileOpenerOptions } from '@capacitor-community/file-opener';

const { t } = useI18n();

const epocStore = useEpocStore();
const settingsStore = useSettingsStore();
const readingStore = useReadingStore();

const { epoc } = storeToRefs(epocStore);
const { readings } = storeToRefs(readingStore);

const route = useRoute();

const { user } = useUser();

onBeforeMount(async () => {
    const id = route.params.epoc_id.toString();
    await epocStore.getEpocById(id);
});

const reading: Ref<Reading | undefined> = ref();
const badgeMode = computed(() => (epoc.value.badges ? Object.keys(epoc.value.badges).length > 0 : false));

const certificateUnlocked = computed(() => {
    if (!epoc.value) return false;

    return badgeMode.value
        ? reading.value?.badges
            ? reading.value.badges.length >= epoc.value.certificateBadgeCount
            : false
        : assessmentData.totalUserScore >= epoc.value.certificateScore;
});

const assessmentData = reactive({
    successStore: 0,
    attemptedScore: 0,
    todoScore: 0,
    totalUserScore: 0,
    totalScore: 0,
});

const badgeModal: Ref<Badge | undefined> = ref();
const showBadgeModal = ref(false);
function showBadgeDetail(badge: Badge) {
    badgeModal.value = badge;
    showBadgeModal.value = true;
}

const loading = ref(false);
async function getCertificate() {
    if (loading.value) {
        presentFail(
            t('PLAYER.SCORE.FAIL_MODAL.HEADER'),
            t('PLAYER.SCORE.FAIL_MODAL.MSG', { score: epoc.value.certificateScore })
        );

        return;
    }

    if (settingsStore.settings.devMode || certificateUnlocked.value) {
        if (!user.value) {
            const userData = await handleSetUser();
            if (!userData) return;
        }

        await presentLoading();
        downloadPdf(await generatePdf(epoc.value, epocStore.rootFolder, unlockedBadges.value));
    }
}

function downloadPdf(doc: jsPDF) {
    const fileName = `attestation-${epoc.value.id}.pdf`;

    if (Capacitor.getPlatform() === 'ios' || Capacitor.getPlatform() === 'android') {
        // Save the PDF to the device
        const output = doc.output('datauristring');
        Filesystem.writeFile({
            path: fileName,
            data: output,
            directory: Directory.Data,
        })
            .then(() => {
                Filesystem.getUri({
                    directory: Directory.Data,
                    path: fileName,
                })
                    .then((getUriResult) => {
                        try {
                            // TODO
                            // const path = getUriResult.uri;
                            // const fileOpenerOptions: FileOpenerOptions = {
                            //     filePath: path,
                            //     contentType: 'application/pdf',
                            //     openWithDefault: true,
                            // };
                            // FileOpener.open(fileOpenerOptions)
                            //     .then(() => {
                            //         dismissLoading();
                            //     })
                            //     .catch(() => {
                            //         dismissLoading().then(() => {
                            //             presentFail(
                            //                 t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                            //                 t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {
                            //                     type: t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.OPEN'),
                            //                 })
                            //             );
                            //         });
                            //     });
                        } catch (e) {
                            dismissLoading().then(() => {
                                presentFail(
                                    t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                                    t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {
                                        type: t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.OPEN'),
                                    })
                                );
                            });
                        }
                    })
                    .catch(() => {
                        dismissLoading().then(() => {
                            presentFail(
                                t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                                t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {
                                    type: t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.RECUP'),
                                })
                            );
                        });
                    });
            })
            .catch(() => {
                dismissLoading().then(() => {
                    presentFail(
                        t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR'),
                        t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_PROMPT', {
                            type: t('PLAYER.SCORE.CERTIFICATE_PDF.ERROR_TYPE.SAVE'),
                        })
                    );
                });
            });
    } else {
        doc.output('dataurlnewwindow');
        dismissLoading();
    }
}

async function presentFail(header: string, message: string) {
    const alert = await alertController.create({
        header,
        message,
        buttons: [t('OK')],
    });

    await alert.present();
}
async function presentLoading() {
    loading.value = true;
    const loadingAlert = await loadingController.create({
        message: t('PLAYER.SCORE.CERTIFICATE_PDF.WAITING'),
    });

    await loadingAlert.present();
}

async function dismissLoading() {
    loading.value = false;
    await loadingController.dismiss();
}

function setAssessmentsData() {
    assessmentData.successStore = 0;
    assessmentData.attemptedScore = 0;
    assessmentData.todoScore = 0;
    assessmentData.totalUserScore = 0;
    assessmentData.totalScore = 0;

    epoc.value.assessments.forEach((assessment) => {
        if (!assessment.questions) {
            return;
        }

        const userAssessment = reading.value?.assessments.find((a) => assessment.id === a.id);
        const scoreTotal = epocStore.calcScoreTotal(epoc.value, assessment.questions);

        assessment.score = getScore(assessment) ?? 0;
        assessment.scoreTotal = getScoreTotal(assessment);

        if (userAssessment && userAssessment.score > 0) {
            assessmentData.totalUserScore += userAssessment.score;
            assessmentData.successStore += userAssessment.score;

            if (userAssessment.score < scoreTotal) {
                assessmentData.attemptedScore += scoreTotal - userAssessment.score;
            }
        } else {
            assessmentData.todoScore += scoreTotal;
        }

        assessmentData.totalScore += scoreTotal;
    });
}

function getScore(content: any) {
    return reading.value?.assessments?.find((assessment) => assessment.id === content.id)?.score ?? null;
}

function getScoreTotal(content: any) {
    return epocStore.calcScoreTotal(epoc.value, content.questions);
}

const unlockedBadges: Ref<uid[]> = ref([]);

watch(
    [epoc, readings],
    ([epocValue, readingsValue]) => {
        if (!epocValue) return;

        if (epocValue && readingsValue) {
            reading.value = readingsValue.find((item) => item.epocId === route.params.id);
        }

        if (!reading.value) {
            readingStore.addReading(epocValue.id);
        }

        if (badgeMode.value) {
            unlockedBadges.value = reading.value ? reading.value.badges : [];
        } else {
            setAssessmentsData();
        }
    },
    { immediate: true }
);
</script>

<template>
    <ion-page>
        <ion-header translucent>
            <ion-toolbar>
                <ion-buttons slot="start">
                    <ion-back-button text="" defaultHref="/library" color="inria-icon" />
                </ion-buttons>
                <ion-title>{{ $t('PLAYER.SCORE.HEADER') }}</ion-title>
            </ion-toolbar>
        </ion-header>

        <ion-content>
            <div class="wrapper" v-if="epoc && !badgeMode && assessmentData">
                <div class="title-container">
                    <div class="title-icon">
                        <ion-icon :icon="starOutline" />
                    </div>
                    <h5 class="title">{{ $t('PLAYER.SCORE.TOTAL_SCORE') }}</h5>
                </div>

                <div class="score">
                    <div class="score-points">{{ assessmentData.totalUserScore }} {{ $t('PLAYER.SCORE.PTS') }}</div>
                    <div class="score-chart">
                        <ScoreProgress
                            :progress="(assessmentData.totalUserScore / assessmentData.totalScore) * 100"
                            :threshold="(epoc.certificateScore / assessmentData.totalScore) * 100"
                            :min-label="0"
                            :max-label="assessmentData.totalScore"
                        />
                    </div>
                </div>

                <template v-if="!epoc.certificateDisabled">
                    <div v-if="!certificateUnlocked" class="certificate">
                        <h5>{{ $t('PLAYER.SCORE.CONTINUE') }}</h5>
                        <p>
                            {{
                                $t('PLAYER.SCORE.REMAINING', {
                                    remaining: epoc.certificateScore - assessmentData.totalUserScore,
                                })
                            }}
                        </p>
                        <ion-button size="default" expand="block" color="medium" fill="outline" @click="getCertificate">
                            <ion-icon :icon="downloadOutline" slot="start" />
                            <span>{{ $t('PLAYER.SCORE.GET_CERTIFICATE') }}</span>
                        </ion-button>
                    </div>

                    <div v-else class="certificate success">
                        <ion-icon class="badge" src="/assets/icon/badge.svg" />
                        <h5>{{ $t('PLAYER.SCORE.CONGRATS') }}</h5>
                        <p>{{ $t('PLAYER.SCORE.CERTIFICATE_WIN') }}</p>
                        <ion-button expand="block" @click="getCertificate">
                            <ion-icon :icon="downloadOutline" slot="start" />
                            <span>{{ $t('PLAYER.SCORE.GET_CERTIFICATE') }}</span>
                        </ion-button>
                    </div>
                </template>

                <div class="short-access">
                    <h4 class="short-access-label">{{ $t('PLAYER.SCORE.PTS_RECAP') }}</h4>
                    <RouterLink
                        v-for="(assessment, index) of epoc.assessments"
                        :key="index"
                        :to="`/epoc/play/${epoc.id}/${assessment.chapterId}/content/${assessment.id}`"
                        class="short-access-item"
                    >
                        <ion-label>
                            {{ assessment.title }}
                            <span>{{ epoc.chapters[assessment.chapterId!].title }}</span>
                        </ion-label>
                        <ion-note
                            :color="
                                assessment?.score !== null && assessment?.score !== undefined
                                    ? (assessment.score ?? 0) < (assessment?.scoreTotal ?? 0)
                                        ? 'inria-certificate'
                                        : 'inria-correct'
                                    : 'inria-icon'
                            "
                            v-if="assessment?.scoreTotal && assessment.scoreTotal > 0"
                        >
                            {{ assessment.score ? assessment.score : 0 }}/{{ assessment.scoreTotal }}
                        </ion-note>
                        <ion-icon :icon="chevronForwardOutline" />
                    </RouterLink>
                </div>
            </div>
            <div v-if="epoc && badgeMode" class="wrapper">
                <div v-if="!certificateUnlocked" class="certificate flex">
                    <div class="certificate-text">
                        <h6>{{ $t('PLAYER.SCORE.CONTINUE') }}</h6>
                        <p>
                            {{
                                $t('PLAYER.SCORE.BADGE_REMAINING', {
                                    remaining: epoc.certificateBadgeCount - unlockedBadges.length,
                                })
                            }}
                        </p>
                    </div>
                    <div class="certificate-badge">
                        <BadgeComponent icon="cert-grey" grey nobg />
                    </div>
                </div>

                <div v-else class="certificate flex success">
                    <pre>reading :{{ reading }}</pre>
                    <div class="certificate-text">
                        <h6>{{ $t('PLAYER.SCORE.CONGRATS') }}</h6>
                        <p>{{ $t('PLAYER.SCORE.CERTIFICATE_WIN') }}</p>
                    </div>
                    <div class="certificate-badge">
                        <BadgeComponent icon="cert" nobg />
                    </div>
                    <ion-button expand="block" @click="getCertificate">
                        <ion-icon :icon="downloadOutline" slot="start" />
                        <span>{{ $t('PLAYER.SCORE.GET_CERTIFICATE') }}</span>
                    </ion-button>
                </div>
                <div class="badge-list">
                    <div
                        v-for="(badge, index) of epoc.badges"
                        :key="index"
                        class="badge-item"
                        :class="{ unlocked: unlockedBadges.includes(badge.id!) }"
                        @click="showBadgeDetail(badge)"
                    >
                        <BadgeComponent
                            :title="badge.title"
                            :icon="badge.icon"
                            :locked="!unlockedBadges.includes(badge.id!)"
                        />
                    </div>
                </div>
            </div>
        </ion-content>
        <BadgeModal v-if="badgeModal" :show-modal="showBadgeModal" :badge="badgeModal" :epoc="epoc" />
    </ion-page>
</template>

<style scoped lang="scss">
.wrapper {
    max-width: 600px;
    margin: auto;
    padding: 1rem;
}

.title-container {
    margin-bottom: 1rem;
    text-align: center;

    .title-icon {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 3rem;
        height: 3rem;
        margin: 0 auto 1rem auto;
        font-size: 1.5rem;
        border-radius: 1rem;
    }

    .title {
        font-size: 1.5rem;
        font-weight: bold;
    }

    &:after {
        content: '';
        display: block;
        width: 80px;
        height: 4px;
        margin: 10px auto;
        border-radius: 2px;
        background: var(--ion-color-inria);
    }
}

.score {
    text-align: center;

    &-points {
        font-size: 2rem;
        font-weight: bold;
    }
}

.certificate {
    position: relative;
    margin: 1rem 0;
    padding: 1rem;
    background: var(--ion-color-contrast);
    border-radius: 0.5rem;

    &.flex {
        display: flex;
        flex-wrap: wrap;
    }

    &-text {
        width: calc(100% - 1rem - 75px);
        margin-right: 1rem;
    }

    &-badge {
        width: 75px;
        flex-shrink: 0;
    }

    ion-button {
        margin-top: 1rem;
    }

    &.success {
        color: white;
        background: var(--ion-color-inria-certificate);

        ion-button {
            width: 100%;
            flex-shrink: 0;
            --background: white;
            --background-activated: var(--ion-color-light);
            --background-focused: var(--ion-color-light);
            ion-icon,
            span {
                color: var(--ion-color-inria-certificate);
            }
        }
    }

    .badge {
        position: absolute;
        top: 1rem;
        right: 0.5rem;
        font-size: 4rem;
    }

    h5 {
        font-size: 2rem;
        font-weight: bold;
    }

    h6 {
        font-size: 1.4rem;
        font-weight: bold;
        margin: 0 0 5px 0;
    }

    p {
        margin: 0;
    }
}

.badge-list {
    display: flex;
    flex-wrap: wrap;
    margin: 0 -5px;
}

.badge-item {
    width: calc(33.333% - 10px);
    margin: 0 5px 20px 5px;
}

.short-access {
    &-label {
        margin-top: 0;
        padding: 0.5em 0 0.25em 0;
        font-size: 1rem;
        font-weight: bold;
        text-transform: uppercase;
        color: var(--ion-color-inria);
        border-bottom: 1px solid var(--ion-color-item);
    }

    &-item {
        display: flex;
        align-items: center;
        padding: 1rem;
        margin-bottom: 0.5rem;
        border-radius: 0.5rem;
        font-weight: bold;
        background: var(--ion-color-item);
        text-decoration: none;
        color: inherit;

        span {
            display: block;
            max-width: 100%;
            font-weight: normal;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
        }

        &:last-child {
            margin-bottom: 0;
        }

        ion-label {
            padding-top: 0.3rem;
            flex-grow: 1;
            max-width: calc(100% - 2.5rem);
        }

        ion-note {
            padding-top: 0.3rem;
            margin: 0 0.5rem;
        }
    }
}
</style>
